### ISSUE TITLE
Julia binaries prebuilt with MKL

### ISSUE THREAD

**Issue by aminya** [JuliaComputing/MKL.jl#10]
Is there any plan to provide ready binaries that have Intel MKL prebuilt in them? If not I can help build binaries for Windows and Linux.

P.S: As I mentioned in my pull requests some people think MKL.jl is not working, and as a result, this is causing lags in other projects. (https://github.com/RoyiAvital/MatlabJuliaMatrixOperationsBenchmark/pull/7)

**Comment by crstnbr** [comment]
AFAIU, there are license issues which prevent JuliaComputing from shipping julia binaries bundled with MKL. See for example [this discourse thread](https://discourse.julialang.org/t/mkl-bundled-julia-by-julia-computing/18585).

**Comment by aminya** [comment]
Well as I said this is not acceptable (anymore).

Python Anaconda ships with MKL-powered libraries:
https://docs.anaconda.com/mkl-optimizations/
https://docs.anaconda.com/anaconda/eula/
https://docs.anaconda.com/mkl-optimizations/eula/

**Comment by StefanKarpinski** [comment]
That is unrelated. Julia itself is built with GPL libraries, making it a derived work under the GPL, which means that if it also included MKL then we would have to comply with GPL for that, which we cannot do. It is possible and desirable to remove those GPL dependencies from Julia, so I encourage you to work on that.
