### ISSUE TITLE
Adding when MKL repository is already downloaded doesn't build automatically

### ISSUE THREAD

**Issue by aminya** [JuliaComputing/MKL.jl#12]
I uninstalled Julia 1.1 and in Julia 1.2 I tried adding MKL using my instructions https://github.com/aminya/MKL.jl/blob/patch-1/README.md#to-install. Adding works fine and it seems the environment gets updated but it does not build. 

So I had to remove MKL folder from .julia\packages\MKL and add MKL again.

**Comment by andreasnoack** [comment]
Did you try `] build MKL`?

**Comment by aminya** [comment]
No, I didn't know that command exists. I should add it to my instructions

**Comment by daxinnan** [comment]
```
(v1.2) pkg> add MKL
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
ERROR: The following package names could not be resolved:
 * MKL (not found in project, manifest or registry)
Please specify by known `name=uuid`.

```

**Comment by aminya** [comment]
@daxinnan follow my instructions for installing MKL: https://github.com/aminya/MKL.jl/tree/patch-1#to-install

P.S: I am not sure why developers don't merge this! 😫

**Comment by aminya** [comment]
@daxinnan MKL repository is updated. For installation refer to the readme: https://github.com/JuliaComputing/MKL.jl#to-install

**Comment by KristofferC** [comment]
This is documented now.
