### ISSUE TITLE
package not registered?

### ISSUE THREAD

**Issue by chriscoey** [JuliaComputing/MKL.jl#13]
```
(v1.4) pkg> add MKL
ERROR: The following package names could not be resolved:
 * MKL (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

**Comment by aminya** [comment]
It is not registered. Use this tutorial for installation:
https://github.com/aminya/MKL.jl/tree/patch-1#to-install

I hope developers finally merge this pull request!

**Comment by andreasnoack** [comment]
Needs to work a little more reliable before we register.

**Comment by aminya** [comment]
@chriscoey MKL repository is updated. For installation refer to the readme: https://github.com/JuliaComputing/MKL.jl#to-install

**Comment by ViralBShah** [comment]
Should this package be registered now?

**Comment by andreasnoack** [comment]
I guess we could do that know. I still don't think we have completely figured out how to handle downstream packages with binary BLAS dependencies but at least wee have *a* way of handling it.

**Comment by ViralBShah** [comment]
Do we need to use one of those jll things nowadays?

**Comment by KristofferC** [comment]
> Do we need to use one of those jll things nowadays?

We do that now.

**Comment by aminya** [comment]
Should we rename the package or we should register the package as it is?
@andreasnoack @KristofferC 

IMO, MKL can be renamed to IntelMKL which gives more context to the name.

**Comment by KristofferC** [comment]
I wonder if the name should include `BLAS` since MKL is big and this is only providing a  part of it, there is also Pardiso.jl and IntelVectorMath.jl, MKLSparse.jl etc.

**Comment by aminya** [comment]
I think `MKL` by itself is pretty describing and we don't really need to change the name. Also see: https://www.google.com/search?client=firefox-b-d&q=mkl

However, I think if all of these packages had `Intel` in their name if it could be more unified and easier for searching (like someone searching intel Julia). This isn't necessary though, just a wish.

**Comment by ViralBShah** [comment]
I guess non blas/lapack wrappers could also be added here.

**Comment by andreasnoack** [comment]
> I wonder if the name should include BLAS since MKL is big and this is only providing a part of it, there is also Pardiso.jl and IntelVectorMath.jl, MKLSparse.jl etc.

I think we are also swapping LAPACK, right? And couldn't the package provide all the references to the shared labraries which are shipped with MKL?

**Comment by waynelapierre** [comment]
what is still holding it from being registered?

**Comment by KristofferC** [comment]
Nothing really except the naming discussion. Note that there is not much to gain from registering it since no package should really depend on this package.

**Comment by ViralBShah** [comment]
Right anything that needs MKL picks it from BB.

**Comment by aminya** [comment]
We should also merge https://github.com/JuliaComputing/MKL.jl/pull/35 before registering. It solves Python interoperability problem.

**Comment by NightMachinary** [comment]
Can there be a section in Julia's docs on packages such as these that essentially provide general-purpose features for everyone, but not included in the default setup because of proprietariness, etc? I guess a lot of people will want to install these if they know about them.

**Comment by ViralBShah** [comment]
Bump on getting this registered. Can we note here which issues are blocking?

**Comment by andreasnoack** [comment]
The registration went through a while ago, see https://github.com/JuliaRegistries/General/tree/master/M/MKL. I just forgot to close this issue.
