### ISSUE TITLE
[question] Where will the mkl libraries be installed?

### ISSUE THREAD

**Issue by kirk86** [JuliaComputing/MKL.jl#21]
Hi and thanks for this.
I have the following questions if you could help me clarify them.

1.) Where is mkl gonna be downloaded and installed?
2.) I have julia installed in a conda-env. Does that make a difference?
3.) If I install conda mkl in the same conda-env that I have julia installed would it be possible to trigger the build `] build MKL` without having to download and install `]add https://github.com/JuliaComputing/MKL.jl` first?

**Comment by andreasnoack** [comment]
Please use discourse.julialang.org for questions.
