### ISSUE TITLE
Not working on Macbook 

### ISSUE THREAD

**Issue by azev77** [JuliaComputing/MKL.jl#26]
I followed all the readme instructions:
```Julia
] add https://github.com/JuliaComputing/MKL.jl
] build MKL
using LinearAlgebra
BLAS.vendor()
```
I got
`:openblas64`

**Comment by andreasnoack** [comment]
Do you get the same after restarting Julia?

**Comment by azev77** [comment]
It works now. Not after the first time restarting Julia though. I restarted a couple times & 
```Julia
using LinearAlgebra
LinearAlgebra.BLAS.set_num_threads(8)
BLAS.vendor()
```

**Comment by andreasnoack** [comment]
Good to hear that it works. Are you using Juno by any chance?

**Comment by azev77** [comment]
Yes I am

**Comment by andreasnoack** [comment]
Juno keeps an extra Julia process running idle to make it faster to restart the REPL. That can be a bit confusing when you've changed something in your setup since the first "new" Julia process after the restart might have been launched before the changes.
