### ISSUE TITLE
Using new PackageCompiler

### ISSUE THREAD

**Issue by aminya** [JuliaComputing/MKL.jl#27]
New PackageCompiler is now on Master. It makes sense to switch to the new system as soon as possible since the old package will not be supported anymore.

**Comment by aminya** [comment]
@daviehh you mentioned you tried the new PackageCompiler (formerly known as X) with MKL. Can you help with this?

**Comment by daviehh** [comment]
Some work-in-progress here: https://github.com/daviehh/MKL.jl/tree/packagecompilerx, only tested on macos, not tested on windows through...
