### ISSUE TITLE
Clean up downloads folder after installation

### ISSUE THREAD

**Issue by thijssteel** [JuliaComputing/MKL.jl#34]
After installation, the downloaded MKL binaries are still left inside /deps/usr/downloads. This amounts to almost 500Mb in my case.

Manually removing these files is easy, but it might be nice for other users to get back some disk space.

**Comment by KristofferC** [comment]
This is fixed on master. It will get downloaded as an artifact and you can use `Pkg.gc()` to clean out unused artifacts.
