### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by CodeLenz** [JuliaComputing/MKL.jl#39]
Hi.

Julia 1.4-rc2 with MKL.jl. Just added PyPlot and ran

> 
> using Pyplot
> plot(rand(100))

gives

> signal (11): Segmentation fault
> in expression starting at REPL[10]:1
> mkl_blas_avx2_dgemm_kernel_nocopy_NN_b0 at /home/lenz/.julia/artifacts/bb7c962f2334afa0b71dc9e4c117315bf1996ac1/lib/libmkl_avx2.so (unknown line)
> Allocations: 39313248 (Pool: 39305012; Big: 8236); GC: 44
> Segmentation fault (core dumped)
>

**Comment by CodeLenz** [comment]
Just reverted MKL with PackageCompiler.restore_default_sysimage() and it is working, so it is really something related to MKL, as stated in the error message.

**Comment by KristofferC** [comment]
You need to use https://github.com/JuliaComputing/MKL.jl/pull/35 for now for python interop.

**Comment by CodeLenz** [comment]
Thank you @KristofferC.  I will take a look
