### ISSUE TITLE
Where did the caveats section go?

### ISSUE THREAD

**Issue by crstnbr** [JuliaComputing/MKL.jl#41]
I remember there was a caveats section in the Readme.md. I can't find it anymore. I doubt that the caveats are gone - please correct me if I'm mistaken. So why has it been removed and what are the current shortcomings of MKL.jl?

**Comment by crstnbr** [comment]
I see https://github.com/JuliaComputing/MKL.jl/pull/17 but new caveats section has not been added yet.

**Comment by aminya** [comment]
They got solved. https://github.com/JuliaComputing/MKL.jl/pull/35 also solves the Python problem.

**Comment by crstnbr** [comment]
That's great news. However, it seems there are some (minor?) side effects, which is why I asked in #35 for clarification of what those are.

**Comment by ViralBShah** [comment]
Let's have a new issue if the registered package needs caveats mentioned in the README.
