### ISSUE TITLE
Build failing on mac with Julia 1.4.2

### ISSUE THREAD

**Issue by ViralBShah** [JuliaComputing/MKL.jl#49]
Just hangs:
```
➜  ~ exec '/Users/viral/Desktop/Julia_Releases/Julia-1.4-mkl.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.2 (2020-05-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.4) pkg> add https://github.com/JuliaComputing/MKL.jl
    Cloning git-repo `https://github.com/JuliaComputing/MKL.jl`
   Updating git-repo `https://github.com/JuliaComputing/MKL.jl`
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
  Installed PackageCompiler ─ v1.1.1
   Updating `~/.julia/environments/v1.4/Project.toml`
  [33e6dc65] + MKL v0.2.0 #master (https://github.com/JuliaComputing/MKL.jl)
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [33e6dc65] + MKL v0.2.0 #master (https://github.com/JuliaComputing/MKL.jl)
  [9b87118b] + PackageCompiler v1.1.1
   Building MKL → `~/.julia/packages/MKL/1edTo/deps/build.log`

```

The log file only has:
```
➜  .julia cat ~/.julia/packages/MKL/1edTo/deps/build.log
######################################################################## 100.0%######################################################################### 100.0%
```

**Comment by andreasnoack** [comment]
Maybe the same as #47

**Comment by ViralBShah** [comment]
Probably

**Comment by johnnychen94** [comment]
Weird, though, I could successfully build it via `git clone` and `dev`:

```julia
 ~/D/J/MKL.jl $ julia --startup=no
...

(@v1.4) pkg> dev .
[ Info: Resolving package identifier `.` as a directory at `~/Documents/Julia/MKL.jl`.
Path `.` exists and looks like the correct package. Using existing path.
  Resolving package versions...
   Updating `~/.julia/environments/v1.4/Project.toml`
  [33e6dc65] + MKL v0.2.0 [`../../../Documents/Julia/MKL.jl`]
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [33e6dc65] + MKL v0.2.0 [`../../../Documents/Julia/MKL.jl`]
  [9b87118b] + PackageCompiler v1.1.1

(@v1.4) pkg> build MKL
   Building MKL → `~/Documents/Julia/MKL.jl/deps/build.log`


 ~/D/J/MKL.jl $ julia --startup=no
...

julia> using LinearAlgebra

julia> BLAS.vendor()
:mkl

julia> versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 8
```

**Comment by phymann** [comment]
> ```
> (@v1.4) pkg> add https://github.com/JuliaComputing/MKL.jl.git
> 
> ...
> 
> ┌ Error: Error building `MKL`: 
> ######################################################################## 100.0% 
> │ error during bootstrap:
> │ LoadError("/var/folders/c0/p23z1x6x3jg_qtqsy_r421y40000gn/T/jl_kbfTr7/sysimage_packagecompiler_a2808ffe-b633-11ea-3b64-47f0cce5c7f1.jl", 16, ArgumentError("Package MKL not found in current path:\n- Run `import Pkg; Pkg.add(\"MKL\")` to install the MKL package.\n"))
> │ require at ./loading.jl:892
> │ do_call at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/libjulia.dylib (unknown line)
> │ eval_body at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/libjulia.dylib (unknown line)
> │ jl_interpret_toplevel_thunk at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/libjulia.dylib (unknown line)
> │ top-level scope at /var/folders/c0/p23z1x6x3jg_qtqsy_r421y40000gn/T/jl_kbfTr7/sysimage_packagecompiler_a2808ffe-b633-11ea-3b64-47f0cce5c7f1.jl:59
> │ jl_toplevel_eval_flex at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/libjulia.dylib (unknown line)
> │ jl_parse_eval_all at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/libjulia.dylib (unknown line)
> │ jl_load at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/libjulia.dylib (unknown line)
> │ exec_program at /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia (unknown line)
> │ true_main at /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia (unknown line)
> │ main at /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia (unknown line)
> │ 
> │ [ Info: Splicing in code to load MKL in /Applications/Julia-1.4.app/Contents/Resources/julia/bin/../share/julia/base/sysimg.jl
> │ [ Info: getting precompile script from: https://raw.githubusercontent.com/JuliaLang/julia/release-1.4/contrib/generate_precompile.jl
> │ [ Info: PackageCompiler: creating base system image (incremental=false)...
> │ ERROR: LoadError: failed process: Process(`/Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia --color=yes --startup-file=no --cpu-target native --sysimage=/var/folders/c0/p23z1x6x3jg_qtqsy_r421y40000gn/T/jl_kbfTr7/corecompiler.ji -g1 -O0 --output-ji=/var/folders/c0/p23z1x6x3jg_qtqsy_r421y40000gn/T/jl_kbfTr7/sys.ji /var/folders/c0/p23z1x6x3jg_qtqsy_r421y40000gn/T/jl_kbfTr7/sysimage_packagecompiler_a2808ffe-b633-11ea-3b64-47f0cce5c7f1.jl`, ProcessExited(1)) [1]
> ```
> 
> Doesn't work.
> 
> However, weird, though, I could successfully build it via `git clone` and `dev`:
> 
> ```julia
>  ~/D/J/MKL.jl $ julia --startup=no
> ...
> 
> (@v1.4) pkg> dev .
> [ Info: Resolving package identifier `.` as a directory at `~/Documents/Julia/MKL.jl`.
> Path `.` exists and looks like the correct package. Using existing path.
>   Resolving package versions...
>    Updating `~/.julia/environments/v1.4/Project.toml`
>   [33e6dc65] + MKL v0.2.0 [`../../../Documents/Julia/MKL.jl`]
>    Updating `~/.julia/environments/v1.4/Manifest.toml`
>   [33e6dc65] + MKL v0.2.0 [`../../../Documents/Julia/MKL.jl`]
>   [9b87118b] + PackageCompiler v1.1.1
> 
> (@v1.4) pkg> build MKL
>    Building MKL → `~/Documents/Julia/MKL.jl/deps/build.log`
> 
> 
>  ~/D/J/MKL.jl $ julia --startup=no
> ...
> 
> julia> using LinearAlgebra
> 
> julia> BLAS.vendor()
> :mkl
> 
> julia> versioninfo()
> Julia Version 1.4.2
> Commit 44fa15b150* (2020-05-23 18:35 UTC)
> Platform Info:
>   OS: macOS (x86_64-apple-darwin18.7.0)
>   CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
> Environment:
>   JULIA_NUM_THREADS = 8
> ```
> 
> here's the build log:
> 
> ```
> Generating precompile statements... 4922 generated in  89.592325 seconds (overhead  64.617657 seconds)
> [ Info: Splicing in code to load MKL in /Applications/Julia-1.4.app/Contents/Resources/julia/bin/../share/julia/base/sysimg.jl
> [ Info: getting precompile script from: https://raw.githubusercontent.com/JuliaLang/julia/release-1.4/contrib/generate_precompile.jl
> [ Info: PackageCompiler: creating base system image (incremental=false)...
> [ Info: PackageCompiler: creating system image object file, this might take a while...
> [ Info: PackageCompiler: default sysimg replaced, restart Julia for the new sysimg to be in effect
> ```

Thank you, this method seems to work both on Linux Mint and Mac for me!

**Comment by MegamindHenry** [comment]
> ```
> (@v1.4) pkg> add https://github.com/JuliaComputing/MKL.jl.git
> 
> ...
> 
> ┌ Error: Error building `MKL`: 
> ######################################################################## 100.0% 
> │ error during bootstrap:
> │ LoadError("/var/folders/c0/p23z1x6x3jg_qtqsy_r421y40000gn/T/jl_kbfTr7/sysimage_packagecompiler_a2808ffe-b633-11ea-3b64-47f0cce5c7f1.jl", 16, ArgumentError("Package MKL not found in current path:\n- Run `import Pkg; Pkg.add(\"MKL\")` to install the MKL package.\n"))
> │ require at ./loading.jl:892
> │ do_call at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/libjulia.dylib (unknown line)
> │ eval_body at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/libjulia.dylib (unknown line)
> │ jl_interpret_toplevel_thunk at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/libjulia.dylib (unknown line)
> │ top-level scope at /var/folders/c0/p23z1x6x3jg_qtqsy_r421y40000gn/T/jl_kbfTr7/sysimage_packagecompiler_a2808ffe-b633-11ea-3b64-47f0cce5c7f1.jl:59
> │ jl_toplevel_eval_flex at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/libjulia.dylib (unknown line)
> │ jl_parse_eval_all at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/libjulia.dylib (unknown line)
> │ jl_load at /Applications/Julia-1.4.app/Contents/Resources/julia/lib/libjulia.dylib (unknown line)
> │ exec_program at /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia (unknown line)
> │ true_main at /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia (unknown line)
> │ main at /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia (unknown line)
> │ 
> │ [ Info: Splicing in code to load MKL in /Applications/Julia-1.4.app/Contents/Resources/julia/bin/../share/julia/base/sysimg.jl
> │ [ Info: getting precompile script from: https://raw.githubusercontent.com/JuliaLang/julia/release-1.4/contrib/generate_precompile.jl
> │ [ Info: PackageCompiler: creating base system image (incremental=false)...
> │ ERROR: LoadError: failed process: Process(`/Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia --color=yes --startup-file=no --cpu-target native --sysimage=/var/folders/c0/p23z1x6x3jg_qtqsy_r421y40000gn/T/jl_kbfTr7/corecompiler.ji -g1 -O0 --output-ji=/var/folders/c0/p23z1x6x3jg_qtqsy_r421y40000gn/T/jl_kbfTr7/sys.ji /var/folders/c0/p23z1x6x3jg_qtqsy_r421y40000gn/T/jl_kbfTr7/sysimage_packagecompiler_a2808ffe-b633-11ea-3b64-47f0cce5c7f1.jl`, ProcessExited(1)) [1]
> ```
> 
> Doesn't work.
> 
> However, weird, though, I could successfully build it via `git clone` and `dev`:
> 
> ```julia
>  ~/D/J/MKL.jl $ julia --startup=no
> ...
> 
> (@v1.4) pkg> dev .
> [ Info: Resolving package identifier `.` as a directory at `~/Documents/Julia/MKL.jl`.
> Path `.` exists and looks like the correct package. Using existing path.
>   Resolving package versions...
>    Updating `~/.julia/environments/v1.4/Project.toml`
>   [33e6dc65] + MKL v0.2.0 [`../../../Documents/Julia/MKL.jl`]
>    Updating `~/.julia/environments/v1.4/Manifest.toml`
>   [33e6dc65] + MKL v0.2.0 [`../../../Documents/Julia/MKL.jl`]
>   [9b87118b] + PackageCompiler v1.1.1
> 
> (@v1.4) pkg> build MKL
>    Building MKL → `~/Documents/Julia/MKL.jl/deps/build.log`
> 
> 
>  ~/D/J/MKL.jl $ julia --startup=no
> ...
> 
> julia> using LinearAlgebra
> 
> julia> BLAS.vendor()
> :mkl
> 
> julia> versioninfo()
> Julia Version 1.4.2
> Commit 44fa15b150* (2020-05-23 18:35 UTC)
> Platform Info:
>   OS: macOS (x86_64-apple-darwin18.7.0)
>   CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
> Environment:
>   JULIA_NUM_THREADS = 8
> ```
> 
> here's the build log:
> 
> ```
> Generating precompile statements... 4922 generated in  89.592325 seconds (overhead  64.617657 seconds)
> [ Info: Splicing in code to load MKL in /Applications/Julia-1.4.app/Contents/Resources/julia/bin/../share/julia/base/sysimg.jl
> [ Info: getting precompile script from: https://raw.githubusercontent.com/JuliaLang/julia/release-1.4/contrib/generate_precompile.jl
> [ Info: PackageCompiler: creating base system image (incremental=false)...
> [ Info: PackageCompiler: creating system image object file, this might take a while...
> [ Info: PackageCompiler: default sysimg replaced, restart Julia for the new sysimg to be in effect
> ```

Thank you, but I still have the same error via `git clone` and `dev` on my Win10 and virtual Debian on it.

`(new) pkg> build MKL
   Building MKL → `~/.julia/packages/MKL/1aXoN/deps/build.log`
┌ Error: Error building `MKL`: 
│ error during bootstrap:
│ LoadError("/tmp/jl_9KiFqC/sysimage_packagecompiler_1359c9c0-15ed-11eb-0b61-130009be5cd4.jl", 16, ArgumentError("Package MKL not found in current path:\n- Run `import Pkg; Pkg.add(\"MKL\")` to install the MKL package.\n"))
│ require at ./loading.jl:893
│ _jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
│ jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
│ jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
│ do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:117
│ eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:206
│ eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:428
│ jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:660
│ top-level scope at /tmp/jl_9KiFqC/sysimage_packagecompiler_1359c9c0-15ed-11eb-0b61-130009be5cd4.jl:63
│ jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:840
│ jl_parse_eval_all at /buildworker/worker/package_linux64/build/src/ast.c:913
│ jl_load_rewrite at /buildworker/worker/package_linux64/build/src/toplevel.c:914
│ exec_program at /buildworker/worker/package_linux64/build/ui/repl.c:45
│ true_main at /buildworker/worker/package_linux64/build/ui/repl.c:118
│ main at /buildworker/worker/package_linux64/build/ui/repl.c:227
│ __libc_start_main at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
│ _start at /home/xuefeng/julia/julia-1.5.0-linux-x86_64/julia-1.5.0/bin/julia (unknown line)
│ 
│ [ Info: Splicing in code to load MKL in /home/xuefeng/julia/julia-1.5.0-linux-x86_64/julia-1.5.0/bin/../share/julia/base/sysimg.jl
│ [ Info: getting precompile script from: https://raw.githubusercontent.com/JuliaLang/julia/release-1.5/contrib/generate_precompile.jl
│ [ Info: PackageCompiler: creating base system image (incremental=false)...
│ ERROR: LoadError: failed process: Process(`/home/xuefeng/julia/julia-1.5.0-linux-x86_64/julia-1.5.0/bin/julia --color=yes --startup-file=no --cpu-target native --sysimage=/tmp/jl_9KiFqC/corecompiler.ji -g1 -O0 --output-ji=/tmp/jl_9KiFqC/sys.ji /tmp/jl_9KiFqC/sysimage_packagecompiler_1359c9c0-15ed-11eb-0b61-130009be5cd4.jl`, ProcessExited(1)) [1]
│ 
│ Stacktrace:
│  [1] pipeline_error at ./process.jl:525 [inlined]
│  [2] read(::Cmd) at ./process.jl:412
│  [3] (::PackageCompiler.var"#2#3"{String,Array{String,1},String,String,String,String})() at /home/xuefeng/.julia/packages/PackageCompiler/AerNj/src/PackageCompiler.jl:157
│  [4] cd(::PackageCompiler.var"#2#3"{String,Array{String,1},String,String,String,String}, ::String) at ./file.jl:104
│  [5] create_fresh_base_sysimage(::Array{String,1}; cpu_target::String) at /home/xuefeng/.julia/packages/PackageCompiler/AerNj/src/PackageCompiler.jl:141
│  [6] create_sysimage(::Array{Symbol,1}; sysimage_path::Nothing, project::String, precompile_execution_file::Array{String,1}, precompile_statements_file::Array{String,1}, incremental::Bool, filter_stdlibs::Bool, replace_default::Bool, cpu_target::String, script::String, base_sysimage::Nothing, isapp::Bool) at /home/xuefeng/.julia/packages/PackageCompiler/AerNj/src/PackageCompiler.jl:417
│  [7] top-level scope at /home/xuefeng/.julia/packages/MKL/1aXoN/src/install.jl:128
│  [8] eval at ./boot.jl:331 [inlined]
│  [9] change_blas_library(::String) at /home/xuefeng/.julia/packages/MKL/1aXoN/src/install.jl:126
│  [10] enable_mkl_startup() at /home/xuefeng/.julia/packages/MKL/1aXoN/src/install.jl:103
│  [11] top-level scope at /home/xuefeng/.julia/packages/MKL/1aXoN/deps/build.jl:9
│  [12] include(::String) at ./client.jl:457
│  [13] top-level scope at none:5
│ in expression starting at /home/xuefeng/.julia/packages/MKL/1aXoN/deps/build.jl:9
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:942
`

**Comment by ViralBShah** [comment]
For 1.5, I have been able to use this package fine. So closing.
