### ISSUE TITLE
package status/stability

### ISSUE THREAD

**Issue by tpapp** [JuliaComputing/MKL.jl#5]
I am making a PR https://github.com/JuliaLang/julia/pull/31570 to the Julia FAQ about BLAS where it was suggested to mention this package.

I thought I would ask the package authors/maintainers if they agree with this. This mostly hinges on whether this package is an experimental/WIP project, or something that is reasonably mature and could provide a solution for the typical reader of that FAQ entry.

**Comment by andreasnoack** [comment]
I think it would make sense to mention this package since I believe this solution would have exactly the same issues as a Julia version built from source against MKL and this package would typically be a much more convenient way to get Julia with MKL.
