### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Jerrywang959** [JuliaComputing/MKL.jl#53]
I installed this packages to test the installing process to help my friends. However, my CPU is AMD CPU. And when I use PyCall. It sends errors that  `Intel MKL ERROR: Parameter 13 was incorrect on entry to SGEMM` . So I want to uninstall it. Do you have any suggestion?

I just typed `rm MKL` .It didn't work.

```julia
julia> using LinearAlgebra

julia> BLAS.vendor()
:mkl
```

**Comment by Jerrywang959** [comment]
I deleted old julia files and downloaded new from 'https://julialang.org/downloads/`. It worked. 
```julia
julia> using LinearAlgebra

julia> BLAS.vendor()
:openblas64

```

Sorry to bother you. I wil close this issue

**Comment by yiyuezhuo** [comment]
I guess that the proper way is to replace updated `sys.so` with old `sys.so.backup` (if no other sysimg was created)? I have not test if everything else works, but `BLAS.vendor() == :openblas64` can be verfied by this.
