### ISSUE TITLE
using existing installed MKL to use in Julia

### ISSUE THREAD

**Issue by rajarshitiwari** [JuliaComputing/MKL.jl#54]
Hi,

It was great to stumble on this package. I was just wondering if one could use somehow the existing MKL installation on local computer (known through $MKLROOT) to provide backend MKL for blas and lapack.

Cheers!

**Comment by andreasnoack** [comment]
It's currently not supported. Generally, using system packages doesn't work well with Julia's _jll binary system but it could probably work in this case if somebody spent a bit of time on it.

**Comment by rajarshitiwari** [comment]
I See. Thanks for the response. Will keep an eye on the github. I myself certainly can't being a novice in julia :smile: , though not for long hopefully!
