### ISSUE TITLE
cannot launch Julia after installing MKL.jl

### ISSUE THREAD

**Issue by JianghuiDu** [JuliaComputing/MKL.jl#6]
Windows 10. Julia v.1.1.0. Just added `MKL.jl`. All seems successful during installation but after that Julia crashed and cannot be launched anymore.

**Comment by JianghuiDu** [comment]
Tried again, here is the error after installation
```
julia> using MKL
[ Info: Precompiling MKL [33e6dc65-8f57-5167-99aa-e5a354878fb2]
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.
ERROR: Failed to precompile MKL [33e6dc65-8f57-5167-99aa-e5a354878fb2] to C:\Users\JD\.julia\compiled\v1.1\MKL\tDGGv.ji.
```

**Comment by andreasnoack** [comment]
Thanks for reporting. I can confirm the issue with Julia 1.1. I used to work with Julia 1.0.2 and I'm now testing it again with 1.0.3.

**Comment by andreasnoack** [comment]
@staticfloat Any idea what could have happened here? I had this working locally on 1.0.2 and AppVeyor passed two months ago with 1.0.3. I can now reproduce this locally with 1.0.2, 1.0.3, and 1.1. What could have changed?

**Comment by staticfloat** [comment]
Can you run inside of `gdb` or `lldb` and tell me where it's crashing?

**Comment by andreasnoack** [comment]
I managed to get a `gdb` but I doubt the result is useful
```
Starting program: /c/Users/andre/AppData/Local/Julia-1.1.0/bin/julia.exe
[New Thread 5324.0x1804]
[New Thread 5324.0x1560]
[New Thread 5324.0x196c]
[New Thread 5324.0xdd4]
[New Thread 5324.0x1404]
[New Thread 5324.0x820]
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.
[Thread 5324.0x1404 exited with code 2]
[Thread 5324.0x820 exited with code 2]
[Thread 5324.0xdd4 exited with code 2]
[Thread 5324.0x196c exited with code 2]
[Inferior 1 (process 5324) exited with code 02]
(gdb) bt
No stack.
```

**Comment by staticfloat** [comment]
Is this only happening on Windows?

**Comment by andreasnoack** [comment]
Yes. It works on Mac and Linux.

**Comment by Elliothuo** [comment]
I encountered the same problem in Julia 1.1.1 (Windows 10). How can I solve this problem?😭

**Comment by KristofferC** [comment]
See the README:

> It is not possible to revert the effect of install MKL.jl. To return to OpenBLAS, it is necessary to reinstall Julia.
