### ISSUE TITLE
Squeeze More Performance from Intel MKL

### ISSUE THREAD

**Issue by RoyiAvital** [JuliaComputing/MKL.jl#7]
Hello,
I don't see the way MKL is built here (I see DLL Open is called, could it be no compilation is done only calling a DLL?).

But it would be great if it is built and compiled into Julia [utilizing more features of Intel MKL to improve performance:](https://software.intel.com/en-us/videos/speed-up-small-matrix-multiplication-using-new-mkl-capabilities)

![image](https://user-images.githubusercontent.com/7347975/57671002-7bd08080-761a-11e9-8d8e-cd782240e9c2.png)

I think the [Packed API](https://software.intel.com/en-us/articles/introducing-the-new-packed-apis-for-gemm) and [Compact API](https://software.intel.com/en-us/articles/intelr-math-kernel-library-introducing-vectorized-compact-routines) are more tricky but if they will be exposed it will be great.

MKL JIT Feature
MKL also has a new JIT feature which I think could be great addition - [Intel® Math Kernel Library Improved Small Matrix Performance Using Just-in-Time (JIT) Code Generation for Matrix Multiplication (GEMM)](https://software.intel.com/en-us/articles/intel-math-kernel-library-improved-small-matrix-performance-using-just-in-time-jit-code).

**Remark**  
It seem you use Intel MKL 2019.0. while Intel MKL 2019.4 is out (OpenMP is even from 2018 release).

**Update (14/10/2019)**  
I listed what I wanted in [Benchmark MATLAB & Julia for Matrix Operations - Message 145](https://discourse.julialang.org/t/benchmark-matlab-julia-for-matrix-operations/2000/145).

**Comment by andreasnoack** [comment]
This is not currently on our to do. It's a relatively low priority since for smaller problems you'd generally like to use `StaticArrays` which would probably be competitive to what MKL can offer for small matrices. Please let us know if you have evidence otherwise.

**Comment by RoyiAvital** [comment]
@andreasnoack ,
Even if `StaticArrays` is competitive, why not enable `MKL_DIRECT_CALL`?
It is only a small compilation flag change.

The other features do something far beyond what you do with `StaticArrays`.
It uses the structure of a small problem (Say multiplying by the same matrix over and over) to get the gains of large size problem.

**Comment by RoyiAvital** [comment]
By the way, there is a simple trick to squeeze better performance from MKL on AMD CPU's.
This is done by replacing the CPU Dispatch function as guided by Agner Fog.

An example for that is given in:

https://github.com/fo40225/Anaconda-Windows-AMD

**Comment by ViralBShah** [comment]
I believe much of the discussion here is out of scope for the current MKL.jl package, and might perhaps find a bit more traction on discourse.

**Comment by RoyiAvital** [comment]
@ViralBShah , What do you mean?
Those features are about integrating MKL into a project.

**Comment by ViralBShah** [comment]
This package is mainly about providing MKL as a replacement for OpenBLAS. For further functionality, other packages can be created that leverage the presence of MKL. For now, I'm going to close this issue.

**Comment by RoyiAvital** [comment]
@ViralBShah , I think you are missing the point.
All the features above must be turned on in the integration of MKL instead of OpenBLAS. They can't be done in a different place.

For instance, the flag for direct call can't be done in later place only on the integration.
