### ISSUE TITLE
How to use MKL Pardiso

### ISSUE THREAD

**Issue by Elliothuo** [JuliaComputing/MKL.jl#9]
I need to solve a large sparse matrix equation system now. As far as I know, `MKL pardiso` is more efficient. I tried to install `Pardiso.jl` in Julia and download `MKL (windows)`, but when I tried an example, Julia reported the following error: 
```julia
Julia has exited. Press Enter to start a new session.
INTEL MKL ERROR: 操作系统无法运行 %1。 mkl_intel_thread.dll.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.
```
Because I didn't know how to solve it, 
(I know this is due to some of my path configuration errors, but I really can't fix this problem on Windows. Maybe you can give me some reference :smile:).
I found MKL. jl. In `README` it said:
> The build step of the package will automatically download Intel MKL and rebuild Julia's system image against Intel MKL. 

So I think I can install `MKL.jl` directly, but I'm not sure if `MKl. jl` includes `Pardiso`?

**Comment by KristofferC** [comment]
MKL.jl is only for BLAS/Lapack. For Pardiso, use Pardiso.jl. Your MKL installation seems to be broken somehow.

**Comment by ViralBShah** [comment]
Since this package is meant only to provide MKL as a BLAS/LAPACK replacement, this issue is out of scope here. One could perhaps have a standard way to install MKL that other packages could leverage. For now, I'm closing this one.
